about/urls.py
from django.conf.urls import url
from django.core.urlresolvers import reverse_lazy
from django.views.generic import RedirectView, TemplateView

app_name = 'about'

urlpatterns = [
    url(r'^$',
        RedirectView.as_view(url=reverse_lazy('about:this_site')),
        name='index'),
    url(r'^this-site/$',
        TemplateView.as_view(template_name='about/this_site.html'),
        name='this_site'),
    url(r'^us/$',
        TemplateView.as_view(template_name='about/us.html'), name='us'),
    url(r'^privacy/$',
        TemplateView.as_view(template_name='about/privacy.html'),
        name='privacy'),
    url(r'^terms/$',
        TemplateView.as_view(template_name='about/terms.html'),
        name='terms'),
    url(r'^contact/$',
        TemplateView.as_view(template_name='about/contact.html'),
        name='contact'),
]

aprigi/urls.py
from django.conf.urls import i18n, include, url
from django.contrib import admin
from django.views.generic import TemplateView


urlpatterns = [
    url(r'^i18n/', include('django.conf.urls.i18n')),
]

urlpatterns += i18n.i18n_patterns(
    url(r'^$', TemplateView.as_view(template_name='homepage.html'),
        name='homepage'),
    url(r'^savings/', include('savings.urls')),
    url(r'^about/', include('about.urls')),
    url(r'^expenses/', include('expenses.urls')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^admin/', admin.site.urls),
)

templates/about/base.html
{% extends "base.html" %}

{% block content %}
  <div class="container">
    <div class="two-columns">
      <div class="main-content">
        <div class="about">
          {% block about-content %}{% endblock %}
        </div>
      </div>

      <div class="sidebar">
        {% include "about/sidebar.html" %}
      </div>
    </div>
  </div>
{% endblock %}

templates/about/contact.html
{% extends "about/base.html" %}
{% load i18n %}

{% block title %}{% trans "Contact us" %}{% endblock %}

{% block header %}
  <div class="page-header">
    <div class="container">
      <h1>{% trans "Contact us" %}</h1>

      <ul class="breadcrumbs">
        <li><a href="{% url 'homepage' %}">
            {% trans "Home" %}
        </a></li>
        <li><a href="{% url 'about:index' %}">
            {% trans "About" %}
        </a></li>
        <li><a href="{% url 'about:contact' %}">
            {% trans "Contact us" %}
        </a></li>
      </ul>
    </div>
  </div>
{% endblock %}

{% block about-content %}
  <h1>{% trans "Contact us" %}</h1>

  <p>
    {% blocktrans %}
      Feel free to email us to provide some feedbacks, give us
      suggestions for new features, or to just say hello!
    {% endblocktrans %}
  </p>

  <div class="contact">
    <a href="mailto:naa@sfc.wide.ad.jp">
      <div class="contact-item">
        <span class="apricon-stack">
          <i class="apricon apricon-circle-thin apricon-stack-2x"></i>
          <i class="apricon apricon-envelope-o apricon-stack-1x"></i>
        </span>
        <p>naa@sfc.wide.ad.jp</p>
      </div>
    </a>

    <a href="https://twitter.com/AnhTranngoc" target="_blank">
      <div class="contact-item">
        <span class="apricon-stack">
          <i class="apricon apricon-circle-thin apricon-stack-2x"></i>
          <i class="apricon apricon-twitter apricon-stack-1x"></i>
        </span>
        <p>@AnhTranngoc</p>
      </div>
    </a>

    <a href="https://github.com/manhhomienbienthuy" target="_blank">
      <div class="contact-item">
        <span class="apricon-stack">
          <i class="apricon apricon-circle-thin apricon-stack-2x"></i>
          <i class="apricon apricon-github-alt apricon-stack-1x"></i>
        </span>
        <p>@manhhomienbienthuy</p>
      </div>
    </a>

    <a href="https://www.facebook.com/manhhomienbienthuy" target="_blank">
      <div class="contact-item">
        <span class="apricon-stack">
          <i class="apricon apricon-circle-thin apricon-stack-2x"></i>
          <i class="apricon apricon-facebook apricon-stack-1x"></i>
        </span>
        <p>Anh Tranngoc</p>
      </div>
    </a>
  </div>
{% endblock %}

templates/about/privacy.html
{% extends "about/base.html" %}
{% load i18n %}

{% block title %}{% trans "Privacy policy" %}{% endblock %}

{% block header %}
  <div class="page-header">
    <div class="container">
      <h1>{% trans "Privacy policy" %}</h1>

      <ul class="breadcrumbs">
        <li><a href="{% url 'homepage' %}">
            {% trans "Home" %}
        </a></li>
        <li><a href="{% url 'about:index' %}">
            {% trans "About" %}
        </a></li>
        <li><a href="{% url 'about:privacy' %}">
            {% trans "Privacy policy" %}
        </a></li>
      </ul>
    </div>
  </div>
{% endblock %}

{% block about-content %}
  {% get_current_language as LANGUAGE_CODE %}
  {% with template="about/privacy_content."|add:LANGUAGE_CODE|add:".html" %}
    {% include  template %}
  {% endwith %}
{% endblock %}

templates/about/sidebar.html
{% load i18n %}

<h1>{% trans "About" %}</h1>

<h2><a href="{% url 'about:this_site' %}">{% trans "About this site" %}</a></h2>
<h2><a href="{% url 'about:us' %}">{% trans "About us" %}</a></h2>
<h2><a href="{% url 'about:terms' %}">{% trans "Terms of use" %}</a></h2>
<h2><a href="{% url 'about:privacy' %}">{% trans "Privacy policy" %}</a></h2>
<h2><a href="{% url 'about:contact' %}">{% trans "Contact us" %}</a></h2>

templates/about/terms.html
{% extends "about/base.html" %}
{% load i18n %}

{% block title %}{% trans "Terms of use" %}{% endblock %}

{% block header %}
  <div class="page-header">
    <div class="container">
      <h1>{% trans "Terms of use" %}</h1>

      <ul class="breadcrumbs">
        <li><a href="{% url 'homepage' %}">
            {% trans "Home" %}
        </a></li>
        <li><a href="{% url 'about:index' %}">
            {% trans "About" %}
        </a></li>
        <li><a href="{% url 'about:terms' %}">
            {% trans "Terms of use" %}
        </a></li>
      </ul>
    </div>
  </div>
{% endblock %}

{% block about-content %}
  {% get_current_language as LANGUAGE_CODE %}
  {% with template="about/terms_content."|add:LANGUAGE_CODE|add:".html" %}
    {% include  template %}
  {% endwith %}
{% endblock %}

templates/about/terms_content.en.html
<h1>Aprigi Terms of Use</h1>

<p>Last modified: June 16, 2016</p>

<h2>Welcome to Aprigi!</h2>
<p>
  Thanks for using our products and services (“Services”). The
  Services are provided by Anh Tranngoc.
</p>
<p>
  By using our Services, you are agreeing to these terms. Please read
  them carefully. If you do not agree with these Terms of Use, your
  sole recourse is to leave the website immediately. A copy of these
  Terms of Use may be downloaded, saved and printed for your
  reference.
</p>

<h2>Using our Services</h2>
<p>
  You must follow any policies made available to you within the
  Services.
</p>
<p>
  Don’t misuse our Services. For example, don’t interfere with our
  Services or try to access them using a method other than the
  interface and the instructions that we provide. You may use our
  Services only as permitted by law, including applicable export and
  re-export control laws and regulations. We may suspend or stop
  providing our Services to you if you do not comply with our terms or
  policies or if we are investigating suspected misconduct.
</p>
<p>
  Using our Services does not give you ownership of any intellectual
  property rights in our Services or the content you access. You may
  not use content from our Services unless you obtain permission from
  its owner or are otherwise permitted by law. These terms do not
  grant you the right to use any branding or logos used in our
  Services. Don’t remove, obscure, or alter any legal notices
  displayed in or along with our Services.
</p>
<p>
  Our Services display some content that is not Aprigi’s. This content
  is the sole responsibility of the entity that makes it available. We
  may review content to determine whether it is illegal or violates
  our policies, and we may remove or refuse to display content that we
  reasonably believe violates our policies or the law. But that does
  not necessarily mean that we review content, so please don’t assume
  that we do.
</p>
<p>
  In connection with your use of the Services, we may send you service
  announcements, administrative messages, and other information. You
  may opt out of some of those communications.
</p>
<p>
  Some of our Services are available on mobile devices. Do not use
  such Services in a way that distracts you and prevents you from
  obeying traffic or safety laws.
</p>

<h2>Your Account</h2>
<p>
  You may need a an account in order to use some of our Services. You
  may create your own account, or your account may be assigned to you
  by an administrator. If you are using an account assigned to you by
  an administrator, different or additional terms may apply and your
  administrator may be able to access or disable your account.
</p>
<p>
  To protect your account, keep your password confidential. You are
  responsible for the activity that happens on or through your
  account. Try not to reuse your account password on third-party
  applications. You agree to immediately notify us of any unauthorized
  use of your password or username or any other breach of security.
</p>

<h2>Privacy and Copyright Protection</h2>
<p>
  Aprigi’s <a href="{% url 'about:privacy' %}">privacy policies</a>
  explain how we treat your personal data and protect your privacy
  when you use our Services. By using our Services, you agree that
  Aprigi can use such data in accordance with our privacy policies.
</p>
<p>
  We respond to notices of alleged copyright infringement and
  terminate accounts of repeat infringers according to the process set
  out in the copyright law and other laws.
</p>
<p>
  We provide information to help copyright holders manage their
  intellectual property online. If you think somebody is violating
  your copyrights and want to notify us, you can find information
  about submitting notices and Aprigi’s policy about responding to
  notices <a href="{% url 'about:contact' %}">in our contact page</a>.
</p>

<h2>Your Content in our Services</h2>
<p>
  Some of our Services allow you to upload, submit, store, send or
  receive content. You retain ownership of any intellectual property
  rights that you hold in that content. In short, what belongs to you
  stays yours.
</p>
<p>
  When you upload, submit, store, send or receive content to or
  through our Services, you give Aprigi (and those we work with) a
  worldwide license to use, host, store, reproduce, modify, create
  derivative works (such as those resulting from translations,
  adaptations or other changes we make so that your content works
  better with our Services), communicate, publish, publicly perform,
  publicly display and distribute such content. The rights you grant
  in this license are for the limited purpose of operating, promoting,
  and improving our Services, and to develop new ones. This license
  continues even if you stop using our Services. Some Services may
  offer you ways to access and remove content that has been provided
  to that Service. Also, in some of our Services, there are terms or
  settings that narrow the scope of our use of the content submitted
  in those Services. Make sure you have the necessary rights to grant
  us this license for any content that you submit to our Services.
</p>
<p>
  If you have an account, we may display your Profile name, Profile
  photo, and actions you take on Aprigi in our Services. We will
  respect the choices you make to limit sharing or visibility settings
  in your account.
</p>
<p>
  You can find more information about how Aprigi uses and stores
  content in the privacy policy or additional terms for particular
  Services. If you submit feedback or suggestions about our Services,
  we may use your feedback or suggestions without obligation to you.
</p>

<h2>Modifying and Terminating our Services</h2>
<p>
  We are constantly changing and improving our Services. We may add or
  remove functionalities or features, and we may suspend or stop a
  Service altogether.
</p>
<p>
  You can stop using our Services at any time, although we’ll be sorry
  to see you go. Aprigi may also stop providing Services to you, or
  add or create new limits to our Services at any time.
</p>
<p>
  We believe that you own your data and preserving your access to such
  data is important. If we discontinue a Service, where reasonably
  possible, we will give you reasonable advance notice and a chance to
  get information out of that Service.
</p>

<h2>Our Warranties and Disclaimers</h2>
<p>
  We provide our Services using a commercially reasonable level of
  skill and care and we hope that you will enjoy using them. But there
  are certain things that we don’t promise about our Services.
</p>
<p>
  OTHER THAN AS EXPRESSLY SET OUT IN THESE TERMS, APRIGI DOES NOT MAKE
  ANY SPECIFIC PROMISES ABOUT THE SERVICES. FOR EXAMPLE, WE DON’T MAKE
  ANY COMMITMENTS ABOUT THE CONTENT WITHIN THE SERVICES, THE SPECIFIC
  FUNCTIONS OF THE SERVICES, OR THEIR RELIABILITY, AVAILABILITY, OR
  ABILITY TO MEET YOUR NEEDS. WE PROVIDE THE SERVICES “AS IS”.
</p>
<p>
  SOME JURISDICTIONS PROVIDE FOR CERTAIN WARRANTIES, LIKE THE IMPLIED
  WARRANTY OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
  NON-INFRINGEMENT. TO THE EXTENT PERMITTED BY LAW, WE EXCLUDE ALL
  WARRANTIES.
</p>

<h2>Liability for our Services</h2>
<p>
  WHEN PERMITTED BY LAW, APRIGI WILL NOT BE RESPONSIBLE FOR LOST
  PROFITS, REVENUES, OR DATA, FINANCIAL LOSSES OR INDIRECT, SPECIAL,
  CONSEQUENTIAL, EXEMPLARY, OR PUNITIVE DAMAGES.
</p>
<p>
  TO THE EXTENT PERMITTED BY LAW, THE TOTAL LIABILITY OF APRIGI FOR
  ANY CLAIMS UNDER THESE TERMS, INCLUDING FOR ANY IMPLIED WARRANTIES,
  IS LIMITED TO THE AMOUNT YOU PAID US TO USE THE SERVICES (OR, IF WE
  CHOOSE, TO SUPPLYING YOU THE SERVICES AGAIN).
</p>
<p>
  IN ALL CASES, APRIGI WILL NOT BE LIABLE FOR ANY LOSS OR DAMAGE THAT
  IS NOT REASONABLY FORESEEABLE.
</p>

<h2>Business uses of our Services</h2>
<p>
  If you are using our Services on behalf of a business, that business
  accepts these terms. It will hold harmless and indemnify Aprigi and
  its affiliates from any claim, suit or action arising from or
  related to the use of the Services or violation of these terms,
  including any liability or expense arising from claims, losses,
  damages, suits, judgments, litigation costs and attorneys’ fees.
</p>

<h2>About these Terms</h2>
<p>
  We may modify these terms, for example, reflect changes to the law
  or changes to our Services. You should look at the terms
  regularly. We’ll post notice of modifications to these terms on this
  page. We’ll post notice of modified additional terms in the
  applicable Service. Changes will not apply retroactively and will
  become effective no sooner than fourteen days after they are
  posted. However, changes addressing new functions for a Service or
  changes made for legal reasons will be effective immediately. If you
  do not agree to the modified terms for a Service, you should
  discontinue your use of that Service.
</p>
<p>
  These terms control the relationship between Aprigi and you. They do
  not create any third party beneficiary rights.
</p>
<p>
  If you do not comply with these terms, and we don’t take action
  right away, this doesn’t mean that we are giving up any rights that
  we may have (such as taking action in the future).
</p>
<p>
  If it turns out that a particular term is not enforceable, this will
  not affect any other terms.
</p>
<p>
  The laws of Vietnam will apply to any disputes arising out of or
  relating to these terms or the Services.
</p>
<p>
  For information about how to contact us, please visit
  our <a href="{% url 'about:contact' %}">contact page</a>.
</p>

templates/about/this_site.html
{% extends "about/base.html" %}
{% load i18n %}

{% block title %}{% trans "About this site" %}{% endblock %}

{% block header %}
  <div class="page-header">
    <div class="container">
      <h1>{% trans "About this site" %}</h1>

      <ul class="breadcrumbs">
        <li><a href="{% url 'homepage' %}">
            {% trans "Home" %}
        </a></li>
        <li><a href="{% url 'about:index' %}">
            {% trans "About" %}
        </a></li>
        <li><a href="{% url 'about:this_site' %}">
            {% trans "About this site" %}
        </a></li>
      </ul>
    </div>
  </div>
{% endblock %}

{% block about-content %}
  {% get_current_language as LANGUAGE_CODE %}
  {% with template="about/this_site_content."|add:LANGUAGE_CODE|add:".html" %}
    {% include  template %}
  {% endwith %}
{% endblock %}

templates/about/this_site_content.en.html
<h1>About Aprigi</h1>

<p>This website and service is dedicated to my April girl.</p>

<p>
  Aprigi is the website and service helps you spend smarter and save
  more. Aprigi will help you pull all your accounts and investments
  into one place so you can track your spending, create a budget and
  get tips for reducing fees and saving money.
</p>

<p>
  Money is very important for life today. Our mission is to empower
  people to make better financial decisions, so they can be good with
  money. Aprigi helps peole keep track of expenses and budgets to
  reach their saving goals. It's simplest way to manage personal
  finances.  Aprigi will help you understand where your money goes, so
  you can plan to spend more effectively. Forget notebook, pen or
  excel sheet, you are able to manage your personal and family finance
  on this website.
</p>

<p>
  Key features:
</p>

<ul>
  <li>Easy to manage and track your Saving</li>
  <li>Calculator in application</li>
  <li>Expense tracker and Money manager</li>
  <li>Budget planner</li>
  <li>It's free (and always will be)</li>
</ul>

<p>
  We try to make the product perfect. But we can not controll all
  potential bugs.  We welcome you to help us improve this website.

  Please see <a href="{% url 'about:contact' %}">Contact us</a> for
  more information about the ways of contact us.
</p>

<p>
  Aprigi is brought to you by Anh Tranngoc. Please see
  <a href="{% url 'about:us' %}">About us</a> for more information
  about the author.
</p>

templates/about/this_site_content.vi.html
<h1>Giới thiệu Aprigi</h1>

<p>Trang web và dịch vụ này dành tặng cô gái tháng Tư của tôi.</p>

<p>
  Aprigi là trang web, cũng là một dịch vụ giúp bạn chi tiêu thông
  minh hơn, và tiết kiệm nhiều hơn. Aprigi sẽ giúp bạn tổng hợp mọi
  tài khoản cũng như các khoản đầu tư tập trung tại một nơi, cho phép
  bạn dễ dàng theo dõi các khoản chi tiêu của mình, tạo ngân sách cho
  các kế hoạch và có mẹo hay để giảm chi phí cũng như tiết kiệm tiền.
</p>

<p>
  Tiền bạc là rất quan trọng trong cuộc sống hôm nay. Nhiệm vụ của
  chúng tôi là giúp mọi người đưa ra quyết định về tài chính tốt hơn,
  và mọi người sẽ giỏi quản lý tiền bạc hơn. Apiri giúp theo dõi các
  khoản chi tiêu và ngân sách để đạt được mục tiêu tiết kiệm của
  bạn. Đây là giải pháp đơn giản nhất để quản lý tài chính cá
  nhân. Aprigi sẽ giúp bạn hiểu tiền của bạn đi đâu và từ đó bạn có
  thể lên kế hoạch chi tiêu hiệu quả hơn. Hãy quên sổ sách và giấy bút
  đi, bạn cũng chẳng cần đến bảng tính Excel nữa, bạn có thể quản lý
  tài chính cá nhân của bạn và gia đình bạn ngay trên trang web này.
</p>

<p>
  Tính năng chính
</p>

<ul>
  <li>Dễ dàng quản lý và theo dõi tiền tiết kiệm của bạn</li>
  <li>Công cụ tính toán ngay trong ứng dụng</li>
  <li>Theo dõi chi tiêu và quản lý tiền bạc</li>
  <li>Dự toán ngân sách</li>
  <li>Dịch vụ này là miễn phí (và sẽ luôn luôn như vậy)</li>
</ul>

<p>
  Chúng tôi cố gắng tạo ra một sản phẩm hoàn hảo. Nhưng chắc chắn vẫn
  còn nhiều lỗi tiềm ẩn mà không tôi chưa giải quyết. Chúng tôi chào
  đón tất cả các bạn sẽ giúp chúng tôi cải thiện trang web này.

  Xin hãy xem phần <a href="{% url 'about:contact' %}">Liên hệ</a> để
  biết thêm các thông tin chi tiết về cách thức liên lạc với chúng
  tôi.
</p>

<p>
  Aprigi được đưa đến bạn bởi Anh Tranngoc. Xin hãy xem phần
  <a href="{% url 'about:us' %}">Về chúng tôi</a> để biết thêm các
  thông tin khác về tác giả.
</p>

templates/about/us.html
{% extends "base.html" %}
{% load staticfiles i18n %}

{% block title %}{% trans "About us" %}{% endblock %}

{% block body-attributes %}
class="about-me {% if user.is_authenticated %}logged-in{% endif %}"
{% endblock %}

{% block content %}
  <div class="container">
    <img class="avatar" src="{% static 'img/avatar.jpg' %}" alt="Anh Tranngoc">
    <h1>Anh Tranngoc</h1>
    <address>
      <a href="http://manhhomienbienthuy.bitbucket.org/" target="_blank">
        http://manhhomienbienthuy.bitbucket.org/
      </a>
      <br>
      <a href="mailto:naa@sfc.wide.ad.jp">naa@sfc.wide.ad.jp</a>
    </address>

    {% get_current_language as LANGUAGE_CODE %}
    {% with template="about/us_content."|add:LANGUAGE_CODE|add:".html" %}
      {% include  template %}
    {% endwith %}
  </div>
{% endblock %}