about/urls.py
from django.conf.urls import url
from django.core.urlresolvers import reverse_lazy
from django.views.generic import RedirectView, TemplateView

app_name = 'about'

urlpatterns = [
    url(r'^$',
        RedirectView.as_view(url=reverse_lazy('about:this_site')),
        name='index'),
    url(r'^this-site/$',
        TemplateView.as_view(template_name='about/this_site.html'),
        name='this_site'),
    url(r'^us/$',
        TemplateView.as_view(template_name='about/us.html'), name='us'),
    url(r'^privacy/$',
        TemplateView.as_view(template_name='about/privacy.html'),
        name='privacy'),
    url(r'^terms/$',
        TemplateView.as_view(template_name='about/terms.html'),
        name='terms'),
    url(r'^contact/$',
        TemplateView.as_view(template_name='about/contact.html'),
        name='contact'),
]

aprigi/urls.py
from django.conf.urls import i18n, include, url
from django.contrib import admin
from django.views.generic import TemplateView


urlpatterns = [
    url(r'^i18n/', include('django.conf.urls.i18n')),
]

urlpatterns += i18n.i18n_patterns(
    url(r'^$', TemplateView.as_view(template_name='homepage.html'),
        name='homepage'),
    url(r'^savings/', include('savings.urls')),
    url(r'^about/', include('about.urls')),
    url(r'^expenses/', include('expenses.urls')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^admin/', admin.site.urls),
)

savings/urls.py
from django.conf.urls import url
from django.core.urlresolvers import reverse_lazy
from django.views.generic import RedirectView

from .views import (PassbookCreateView, PassbookDeleteView, PassbookUpdateView,
                    PassbookView, PassbookWithdrawView)

app_name = 'savings'

urlpatterns = [
    url(r'^$', RedirectView.as_view(url=reverse_lazy('savings:passbook_list')),
        name='index'),
    url(r'^passbook/$', PassbookView.as_view(), name='passbook_list'),
    url(r'^passbook/create$', PassbookCreateView.as_view(),
        name='passbook_create'),
    url(r'^passbook/(?P<pk>\d+)/update$', PassbookUpdateView.as_view(),
        name='passbook_update'),
    url(r'^passbook/(?P<pk>\d+)/delete$', PassbookDeleteView.as_view(),
        name='passbook_delete'),
    url(r'^passbook/withdraw$', PassbookWithdrawView.as_view(),
        name='passbook_withdraw'),
]

savings/models.py
from calendar import monthrange
from datetime import datetime

from django.db import models
from django.dispatch import receiver
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _

DAYS_PER_YEAR = 365
DAYS_PER_WEEK = 7
MONTHS_PER_YEAR = 12


class Passbook(models.Model):
    WEEK = 1
    MONTH = 2
    PERIOD_TYPE_CHOICES = (
        (WEEK, _('Week')),
        (MONTH, _('Month')),
    )
    DEFAULT_PERIOD_TYPE = MONTH

    number = models.CharField(_('number'), max_length=30, unique=True,
                              db_index=True)
    account_number = models.CharField(_('account number'),
                                      max_length=30, unique=True,
                                      db_index=True)
    amount = models.IntegerField(_('amount'))
    period_type = models.IntegerField(_('period type'),
                                      choices=PERIOD_TYPE_CHOICES,
                                      default=DEFAULT_PERIOD_TYPE)
    period = models.IntegerField(_('period'))
    rate = models.FloatField(_('rate'))
    start_date = models.DateField(_('start date'))
    stop_date = models.DateField(_('stop date'))
    is_open = models.BooleanField(_('is open'), default=True,
                                  db_index=True)
    notes = models.CharField(_('notes'), max_length=200)

    class Meta:
        verbose_name = _('Passbook')
        verbose_name_plural = _('Passbooks')

    def __str__(self):
        return self.number

    def interest(self):
        if not self.is_open or self.period_type not in (self.WEEK, self.MONTH):
            return None
        if self.period_type == self.WEEK:
            return round(self.amount * self.rate / 100 / DAYS_PER_YEAR *
                         self.period * 7)
        return round(self.amount * self.rate / 100 / MONTHS_PER_YEAR *
                     self.period)
    interest.short_description = _('interest (expected)')

    def interest_on_withdraw(self, date):
        if not self.is_open or self.period_type not in (self.WEEK, self.MONTH):
            return None

        RATE_OUT_PERIOD = 0.6
        base, interval_in_period, interval_out_period = self._get_info(date)
        total_after_period = self.amount * \
            (1 + self.rate / 100 / base * self.period) ** interval_in_period
        total = total_after_period * \
            (1 + RATE_OUT_PERIOD / 100 / DAYS_PER_YEAR) ** interval_out_period
        return round(total - self.amount)

    def _get_info(self, date):
        if self.period_type == self.WEEK:
            return self._get_info_week(date)
        else:
            return self._get_info_month(date)

    def _get_info_week(self, date):
        base = DAYS_PER_YEAR / DAYS_PER_WEEK
        interval = (date - self.start_date).days
        interval_in_period = interval // (DAYS_PER_WEEK * self.period)
        interval_out_period = interval - \
            interval_in_period * DAYS_PER_WEEK * self.period
        return base, interval_in_period, interval_out_period

    def _get_info_month(self, date):
        base = MONTHS_PER_YEAR
        interval = date.month - self.start_date.month + \
            MONTHS_PER_YEAR * (date.year - self.start_date.year) - \
            (date.day < self.start_date.day)
        interval_in_period = interval // self.period
        stop_year = self.start_date.year + \
            (self.start_date.month + interval_in_period > MONTHS_PER_YEAR)
        stop_month = (self.start_date.month +
                      interval_in_period * self.period) % MONTHS_PER_YEAR
        if stop_month == 0:
            stop_month = 12
        stop_month_range = monthrange(stop_year, stop_month)[1]
        if self.start_date.day < stop_month_range:
            stop_day = self.start_date.day
        else:
            stop_day = stop_month_range
        interval_out_period = (
            date - datetime(stop_year, stop_month, stop_day).date()).days
        return base, interval_in_period, interval_out_period


class Withdraw(models.Model):
    amount = models.IntegerField(_('amount'))
    date = models.DateField(_('withdrawn on'), default=timezone.now)
    is_open = models.BooleanField(_('is open'), default=True, db_index=True)

    class Meta:
        verbose_name = _('Withdraw')
        verbose_name_plural = _('Withdraws')

    def __str__(self):
        return "${obj.amount} on {obj.date}".format(obj=self)


@receiver(models.signals.post_save, sender=Passbook,
          dispatch_uid='update_withdraw')
def update_withdraw(sender, instance, created, **kwargs):
    if created and instance.is_open:
        Withdraw.objects.filter(is_open=True).update(is_open=False)


class Objective(models.Model):
    year = models.IntegerField(_('year'), unique=True, db_index=True)
    amount = models.IntegerField(_('amount'), null=True)

    class Meta:
        verbose_name = _('Objective')
        verbose_name_plural = _('Objectives')

    def __str__(self):
        return "${obj.amount} for the year {obj.year}".format(obj=self)

savings/forms.py
from django import forms
from django.core.exceptions import SuspiciousOperation
from django.utils import timezone

from .models import Passbook, Withdraw


class PassbookForm(forms.ModelForm):

    class Meta:
        model = Passbook
        fields = '__all__'


class PassbookSearchForm(forms.Form):
    is_open = forms.NullBooleanField()
    upcoming = forms.DateField(
        required=False, initial=timezone.now().strftime('%Y-%m-%d'))


class PassbookWithdrawForm(forms.Form):
    date = forms.DateField(
        required=True, initial=timezone.now().strftime('%Y-%m-%d'))

    def get_passbook_list(self):
        object_list = Passbook.objects.all().filter(is_open=True)
        if not self.is_valid():
            raise SuspiciousOperation("Invalid date input")
        target_date = self.cleaned_data.get('date')
        return object_list.filter(stop_date__lte=target_date)

    def do_withdraw(self):
        object_list = self.get_passbook_list()
        total = sum(passbook.amount + passbook.interest_on_withdraw(
            self.cleaned_data['date']) for passbook in object_list)
        object_list.update(is_open=False)
        return Withdraw.objects.create(
            amount=total,
            date=self.cleaned_data['date'],
            is_open=True,
        )

savings/views.py
from calendar import monthrange
from datetime import timedelta

from django.contrib.auth.mixins import (LoginRequiredMixin,
                                        PermissionRequiredMixin)
from django.core.urlresolvers import reverse
from django.utils import timezone
from django.views.generic import (CreateView, DeleteView, FormView, ListView,
                                  UpdateView)

from .forms import PassbookForm, PassbookSearchForm, PassbookWithdrawForm
from .models import Passbook


class PassbookView(LoginRequiredMixin, ListView):
    model = Passbook

    def get_queryset(self):
        object_list = self.model.objects.all().order_by('-start_date')
        form = PassbookSearchForm(self.request.GET or None)
        if form.is_valid():
            is_open = form.cleaned_data.get('is_open')
            if is_open is not None:
                object_list = object_list.filter(is_open=is_open)
            target_date = form.cleaned_data.get('upcoming')
            if target_date:
                object_list = object_list.filter(is_open=True,
                                                 stop_date__lte=target_date)
        return object_list

    def get_context_data(self):
        context = super().get_context_data()
        context.update(self._upcoming_date())
        context.update(self._origin_and_interest())
        submitted_date = self.request.GET.get(
            'upcoming', timezone.now().strftime('%Y-%m-%d'))
        context.update({
            'form': PassbookSearchForm({'upcoming': submitted_date}),
        })
        return context

    def _upcoming_date(self):
        today = timezone.now()
        end_date_of_month = monthrange(today.year, today.month)[1]
        end_of_month = "{year:04d}-{month:02d}-{day:02d}".format(
            year=today.year,
            month=today.month,
            day=end_date_of_month,
        )
        return {
            'thisweek': (today + timedelta(days=7)).strftime('%Y-%m-%d'),
            'thismonth': end_of_month,
        }

    def _origin_and_interest(self):
        origin = interest = 0
        for passbook in self.object_list:
            origin += passbook.amount if passbook.is_open else 0
            interest += passbook.interest() or 0
        return {
            'origin': origin,
            'interest': interest,
        }


class PassbookCreateView(LoginRequiredMixin,
                         PermissionRequiredMixin,
                         CreateView):
    model = Passbook
    form_class = PassbookForm
    permission_required = 'savings.add_passbook'

    def get_success_url(self):
        return reverse('savings:passbook_list')


class PassbookUpdateView(LoginRequiredMixin,
                         PermissionRequiredMixin,
                         UpdateView):
    model = Passbook
    form_class = PassbookForm
    permission_required = 'savings.change_passbook'

    def get_success_url(self):
        return reverse('savings:passbook_list')


class PassbookDeleteView(LoginRequiredMixin,
                         PermissionRequiredMixin,
                         DeleteView):
    model = Passbook
    permission_required = 'savings.delete_passbook'

    def get_success_url(self):
        return reverse('savings:passbook_list')


class PassbookWithdrawView(LoginRequiredMixin,
                           PermissionRequiredMixin,
                           FormView):
    form_class = PassbookWithdrawForm
    template_name = 'savings/passbook_withdraw.html'
    permission_required = ('savings.change_passbook', 'savings.add_withdraw')

    def get_context_data(self):
        context = super().get_context_data()
        form = self.form_class(self.request.GET or None)
        object_list = form.get_passbook_list()
        origin = interest = 0
        for passbook in object_list:
            origin += passbook.amount
            interest += passbook.interest_on_withdraw(
                form.cleaned_data['date'])
        context.update({
            'object_list': object_list,
            'form': form,
            'origin': origin,
            'interest': interest,
        })
        return context

    def form_valid(self, form):
        form.do_withdraw()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('savings:passbook_list')

templates/savings/passbook_confirm_delete.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
  {% trans "Delete passbook" %} | {% trans "Savings" %}
{% endblock %}

{% block header %}
  <div class="page-header">
    <div class="container">
      <h1>{% trans "Delete passbook" %}</h1>

      <ul class="breadcrumbs">
        <li><a href="{% url 'homepage' %}">
          {% trans "Home" %}
        </a></li>
        <li><a href="{% url 'savings:index' %}">
          {% trans "Savings" %}
        </a></li>
        <li><a href="{% url 'savings:passbook_list' %}">
          {% trans "Passbook" %}
        </a></li>
        <li><a href="{% url 'savings:passbook_delete' object.id %}">
          {% trans "Delete passbook" %}
        </a></li>
      </ul>
    </div>
  </div>
{% endblock %}

{% block content %}
  <div class="container">
    <h1>{% trans "Are you sure?" %}</h1>
    <p>
      {% blocktrans %}
        Are you sure you want to delete the selected Passbook? All of
        the following objects and their related items will be deleted.
      {% endblocktrans %}
    </p>

    <form action="" method="post" class="form-general">
      {% csrf_token %}
      <div>
        <ul>
          <li>
            <strong>{% trans "number"|title %}:</strong>
            {{ object.number }}
          </li>
          <li>
            <strong>{% trans "account number"|title %}:</strong>
            {{ object.account_number }}
          </li>
          <li>
            <strong>{% trans "amount"|title %}:</strong>
            {{ object.amount }}
          </li>
          <li>
            <strong>{% trans "period"|title %}:</strong>
            {{ object.period }}
          </li>
          <li>
            <strong>{% trans "start date"|title %}:</strong>
            {{ object.start_date }}
          </li>
          <li>
            <strong>{% trans "stop date"|title %}:</strong>
            {{ object.stop_date }}
          </li>
          <li>
            <strong>{% trans "is open"|title %}:</strong>
            {{ object.is_open }}
          </li>
        </ul>
      </div>

      <button class="button button-primary">
        {% trans "Yes, I'm sure" %}
      </button>
      <a href="{% url 'savings:passbook_list' %}" class="button button-secondary">
        {% trans "No, take me back" %}
      </a>
    </form>
  </div>
{% endblock %}

templates/savings/passbook_form.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
  {% if object %}
    {% trans "Update passbook" %}
  {% else %}
    {% trans "Add new passbook" %}
  {% endif %}
  | {% trans "Savings" %}
{% endblock %}

{% block header %}
  <div class="page-header">
    <div class="container">
      <h1>
        {% if object %}
          {% trans "Update passbook" %}
        {% else %}
          {% trans "Add new passbook" %}
        {% endif %}
      </h1>

      <ul class="breadcrumbs">
        <li><a href="{% url 'homepage' %}">
          {% trans "Home" %}
        </a></li>
        <li><a href="{% url 'savings:index' %}">
          {% trans "Savings" %}
        </a></li>
        <li><a href="{% url 'savings:passbook_list' %}">
          {% trans "Passbook" %}
        </a></li>
        <li>
          {% if object %}
            <a href="{% url 'savings:passbook_update' object.id %}">
              {% trans "Update passbook" %}
            </a>
          {% else %}
            <a href="{% url 'savings:passbook_create' %}">
              {% trans "Add new passbook" %}
            </a>
          {% endif %}
        </li>
      </ul>
    </div>
  </div>
{% endblock %}

{% block content %}
  <div class="container">
    {% if withdrawn %}
      <div class="warning">
        <p>
          {% blocktrans %}
            You have withdrawn ${{ withdrawn }}
            without creating any new passbook.
          {% endblocktrans %}
        </p>
      </div>
    {% endif %}

    <h1>
      {% if object %}
        {% trans "Update passbook" %}
      {% else %}
        {% trans "Add new passbook" %}
      {% endif %}
    </h1>

    <form action="" method="post" class="form-general">
      {% csrf_token %}

      {% if form.errors %}
        <p class="error">{% trans "Please correct the errors below" %}</p>
        {{ form.non_field_errors }}
      {% endif %}

      {% for field in form %}
        <div>
          {{ field.label_tag }}
          {% if field.errors %}
            <span class="error">
              {{ field.errors.0 }}
            </span>
          {% endif %}
          {{ field }}
        </div>
      {% endfor %}

      <button class="button button-primary">
        {% if object %}
          <i class="apricon apricon-pencil"></i>
          {% trans "Update passbook" %}
        {% else %}
          <i class="apricon apricon-plus"></i>
          {% trans "Add new passbook" %}
        {% endif %}
      </button>
    </form>
  </div>
{% endblock %}

templates/savings/passbook_list.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
  {% trans "Passbook list" %} | {% trans "Savings" %}
{% endblock %}

{% block header %}
  <div class="page-header">
    <div class="container">
      <h1>{% trans "Passbook list" %}</h1>

      <ul class="breadcrumbs">
        <li><a href="{% url 'homepage' %}">
          {% trans "Home" %}
        </a></li>
        <li><a href="{% url 'savings:index' %}">
          {% trans "Savings" %}
        </a></li>
        <li><a href="{% url 'savings:passbook_list' %}">
          {% trans "Passbook" %}
        </a></li>
        <li><a href="{% url 'savings:passbook_list' %}">
          {% trans "Passbook list" %}
        </a></li>
      </ul>
    </div>
  </div>
{% endblock %}

{% block content %}
  <div class="container">
    {% if withdrawn %}
      <div class="warning">
        <p>
          {% blocktrans %}
            You have withdrawn ${{ withdrawn }}
            without creating any new passbook.
          {% endblocktrans %}
        </p>
      </div>
    {% endif %}

    <div class="object-tools">
      <a href="{% url 'savings:passbook_create' %}"
         class="button button-secondary">
        <i class="apricon apricon-plus"></i>
        {% trans "Add new passbook" %}
      </a>

      <form class="form-input" action="{% url 'savings:passbook_withdraw' %}"
            method="get">
        <input name="date" type="date" placeholder="yyyy-mm-dd"
               value="{{ form.upcoming.value }}">
        <button type="submit">
          <i class="apricon apricon-money"></i>
          <span class="visuallyhidden">{% trans "Withdraw" %}</span>
        </button>
      </form>
    </div>

    <h1>{% trans "Passbook list" %}</h1>
    <p>
      {% blocktrans count counter=object_list|length %}
        You have total {{ counter }} passbook.
      {% plural %}
        You have total {{ counter }} passbooks.
      {% endblocktrans %}
    </p>
    <p>
      {% blocktrans %}
        With total amount of: <strong>${{ origin }}</strong><br>
        and total interest of: <strong>${{ interest }}</strong>.
      {% endblocktrans %}
    </p>

    <div class="two-columns">
      <div class="main-content">
        {% include "savings/passbook_list_table.html" %}
      </div>

      <div class="sidebar">
        {% include "savings/passbook_list_sidebar.html" %}
      </div>
    </div>
  </div>
{% endblock %}

templates/savings/passbook_list_sidebar.html
{% load i18n %}

<h1>{% trans "Filter" %}</h1>

<h2>{% trans "By status" %}</h2>
<ul>
  <li><a href="?">{% trans "All" %}</a></li>
  <li><a href="?is_open=2">{% trans "Passbook open" %}</a></li>
  <li><a href="?is_open=3">{% trans "Passbook close" %}</a></li>
</ul>

<h2>{% trans "Upcoming" %}</h2>
<ul>
  <li><a href="?">{% trans "All" %}</a></li>
  <li><a href="?upcoming={% now 'Y-m-d' %}">{% trans "Today" %}</a></li>
  <li><a href="?upcoming={{ thisweek }}">{% trans "One week" %}</a></li>
  <li><a href="?upcoming={{ thismonth }}">{% trans "This month" %}</a></li>
  <li><a href="?upcoming={% now 'Y' %}-12-31">{% trans "This year" %}</a></li>
  <li>
    <form class="form-input" action="?" method="get">
      <input name="upcoming" placeholder="yyyy-mm-dd" type="date"
             value="{{ form.upcoming.value }}" required>
      <button type="submit">
        <i class="apricon apricon-search"></i>
        <span class="visuallyhidden">{% trans "Search" %}</span>
      </button>
    </form>
  </li>
</ul>

templates/savings/passbook_list_table.html
{% load i18n %}

<div class="responsive-table">
  <table>
    <thead>
      <tr>
        <th>{% trans "number" %}</th>
        <th>{% trans "account number" %}</th>
        <th>{% trans "amount" %}</th>
        <th>{% trans "period" %}</th>
        <th>{% trans "rate" %}</th>
        <th>{% trans "start date" %}</th>
        <th>{% trans "stop date" %}</th>
        <th>{% trans "is open" %}</th>
        <th>{% trans "interest (expected)" %}</th>
        <th>{% trans "Action" %}</th>
      </tr>
    </thead>

    <tbody>
      {% for passbook in object_list %}
        <tr{% if not passbook.is_open %} class="grayout"{% endif %}>
          <td>{{ passbook.number }}</td>
          <td>{{ passbook.account_number }}</td>
          <td class="right">{{ passbook.amount }}</td>
          <td>
            {% if passbook.period_type == passbook.MONTH %}
              {% blocktrans count counter=passbook.period %}
                {{ counter }} month
              {% plural %}
                {{ counter }} months
              {% endblocktrans %}
            {% elif passbook.period_type == passbook.WEEK %}
              {% blocktrans count counter=passbook.period %}
                {{ counter }} week
              {% plural %}
                {{ counter }} weeks
              {% endblocktrans %}
            {% endif %}
          </td>
          <td>{{ passbook.rate }}%</td>
          <td>{{ passbook.start_date }}</td>
          <td>{{ passbook.stop_date }}</td>
          <td class="center">
            {% if passbook.is_open %}
              <i class="apricon apricon-check-circle"></i>
            {% else %}
              <i class="apricon apricon-times-circle"></i>
            {% endif %}
          </td>
          <td>{{ passbook.interest|default_if_none:"-" }}</td>
          <td>
            <p><a href="{% url 'savings:passbook_update' passbook.id %}">
              {% trans "Change" %}
            </a></p>
            <p><a href="{% url 'savings:passbook_delete' passbook.id %}">
              {% trans "Delete" %}
            </a></p>
          </td>
        </tr>
      {% empty %}
        <tr>
          <td class="center" colspan="10">{% trans "No passbooks available" %}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

templates/savings/passbook_withdraw.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
  {% trans "Withdraw" %} | {% trans "Savings" %}
{% endblock %}

{% block header %}
  <div class="page-header">
    <div class="container">
      <h1>{% trans "Withdraw" %}</h1>

      <ul class="breadcrumbs">
        <li><a href="{% url 'homepage' %}">
          {% trans "Home" %}
        </a></li>
        <li><a href="{% url 'savings:index' %}">
          {% trans "Savings" %}
        </a></li>
        <li><a href="{% url 'savings:passbook_list' %}">
          {% trans "Passbook" %}
        </a></li>
        <li><a href="{% url 'savings:passbook_withdraw' %}">
          {% trans "Withdraw" %}
        </a></li>
      </ul>
    </div>
  </div>
{% endblock %}

{% block content %}
  <div class="container">
    <div class="object-tools">
      <form class="form-input" action="" method="get">
        <input name="date" type="date" placeholder="yyyy-mm-dd"
               value="{{ form.date.value }}">
        <button type="submit">
          <i class="apricon apricon-money"></i>
          <span class="visuallyhidden">{% trans "Withdraw" %}</span>
        </button>
      </form>
    </div>

    <h1>{% trans "Withdraw" %}</h1>
    <p>
      {% blocktrans count counter=object_list|length %}
        You have total {{ counter }} passbook.
      {% plural %}
        You have total {{ counter }} passbooks.
      {% endblocktrans %}
    </p>
    <p>
      {% blocktrans %}
        With total amount of: <strong>${{ origin }}</strong><br>
        and total interest of: <strong>${{ interest }}</strong>.
      {% endblocktrans %}
    </p>

    {% include "savings/passbook_withdraw_table.html" %}

    <p>{% trans "Are you sure?" %}</p>
    <form class="form-general" action="" method="post">
      {% csrf_token %}
      {{ form.date.as_hidden }}
      <button class="button button-primary">
        {% trans "Yes, I'm sure" %}
      </button>
      <a href="{% url 'savings:passbook_list' %}" class="button button-secondary">
        {% trans "No, take me back" %}
      </a>
    </form>
  </div>
{% endblock %}

templates/savings/passbook_withdraw_table.html
{% load i18n savings %}

<div class="responsive-table">
  <table>
    <thead>
      <tr>
        <th>{% trans "number" %}</th>
        <th>{% trans "account number" %}</th>
        <th>{% trans "amount" %}</th>
        <th>{% trans "period" %}</th>
        <th>{% trans "rate" %}</th>
        <th>{% trans "start date" %}</th>
        <th>{% trans "stop date" %}</th>
        <th>{% trans "interest" %}</th>
      </tr>
    </thead>

    <tbody>
      {% for passbook in object_list %}
        <tr{% if not passbook.is_open %} class="grayout"{% endif %}>
          <td>{{ passbook.number }}</td>
          <td>{{ passbook.account_number }}</td>
          <td class="right">{{ passbook.amount }}</td>
          <td>
            {% if passbook.period_type == passbook.MONTH %}
              {% blocktrans count counter=passbook.period %}
                {{ counter }} month
              {% plural %}
                {{ counter }} months
              {% endblocktrans %}
            {% elif passbook.period_type == passbook.WEEK %}
              {% blocktrans count counter=passbook.period %}
                {{ counter }} week
              {% plural %}
                {{ counter }} weeks
              {% endblocktrans %}
            {% endif %}
          </td>
          <td>{{ passbook.rate }}%</td>
          <td>{{ passbook.start_date }}</td>
          <td>{{ passbook.stop_date }}</td>
          <td>
            {{ passbook|interest_on_withdraw:form.date.value|default_if_none:"-" }}
          </td>
        </tr>
      {% empty %}
        <tr>
          <td class="center" colspan="8">{% trans "No passbooks available" %}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
</div>