about/urls.py
from django.conf.urls import url
from django.core.urlresolvers import reverse_lazy
from django.views.generic import RedirectView, TemplateView

app_name = 'about'

urlpatterns = [
    url(r'^$',
        RedirectView.as_view(url=reverse_lazy('about:this_site')),
        name='index'),
    url(r'^this-site/$',
        TemplateView.as_view(template_name='about/this_site.html'),
        name='this_site'),
    url(r'^us/$',
        TemplateView.as_view(template_name='about/us.html'), name='us'),
    url(r'^privacy/$',
        TemplateView.as_view(template_name='about/privacy.html'),
        name='privacy'),
    url(r'^terms/$',
        TemplateView.as_view(template_name='about/terms.html'),
        name='terms'),
    url(r'^contact/$',
        TemplateView.as_view(template_name='about/contact.html'),
        name='contact'),
]

aprigi/urls.py
from django.conf.urls import i18n, include, url
from django.contrib import admin
from django.views.generic import TemplateView


urlpatterns = [
    url(r'^i18n/', include('django.conf.urls.i18n')),
]

urlpatterns += i18n.i18n_patterns(
    url(r'^$', TemplateView.as_view(template_name='homepage.html'),
        name='homepage'),
    url(r'^savings/', include('savings.urls')),
    url(r'^about/', include('about.urls')),
    url(r'^expenses/', include('expenses.urls')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^admin/', admin.site.urls),
)

expenses/urls.py
from django.conf.urls import url
from django.core.urlresolvers import reverse_lazy
from django.views.generic import RedirectView

from .views import BalanceView

app_name = 'expenses'

urlpatterns = [
    url(r'^$', RedirectView.as_view(url=reverse_lazy('expenses:balance_list')),
        name='index'),
    url(r'^balance/$', BalanceView.as_view(), name='balance_list'),
]

savings/urls.py
from django.conf.urls import url
from django.core.urlresolvers import reverse_lazy
from django.views.generic import RedirectView

from .views import (PassbookCreateView, PassbookDeleteView, PassbookUpdateView,
                    PassbookView, PassbookWithdrawView)

app_name = 'savings'

urlpatterns = [
    url(r'^$', RedirectView.as_view(url=reverse_lazy('savings:passbook_list')),
        name='index'),
    url(r'^passbook/$', PassbookView.as_view(), name='passbook_list'),
    url(r'^passbook/create$', PassbookCreateView.as_view(),
        name='passbook_create'),
    url(r'^passbook/(?P<pk>\d+)/update$', PassbookUpdateView.as_view(),
        name='passbook_update'),
    url(r'^passbook/(?P<pk>\d+)/delete$', PassbookDeleteView.as_view(),
        name='passbook_delete'),
    url(r'^passbook/withdraw$', PassbookWithdrawView.as_view(),
        name='passbook_withdraw'),
]

templates/includes/footer.html
{% load i18n %}

<footer>
  <div class="container">
    <ul class="links">
      <li><a href="{% url 'about:this_site' %}">{% trans "About this site" %}</a></li>
      <li><a href="{% url 'about:us' %}">{% trans "About us" %}</a></li>
      <li><a href="{% url 'about:terms' %}">{% trans "Terms of use" %}</a></li>
      <li><a href="{% url 'about:privacy' %}">{% trans "Privacy policy" %}</a></li>
      <li><a href="{% url 'about:contact' %}">{% trans "Contact us" %}</a></li>
    </ul>

    <ul class="socials">
      <li><a href="https://www.facebook.com/manhhomienbienthuy" target="_blank">
        <span class="apricon-stack">
          <i class="apricon apricon-circle-thin apricon-stack-2x"></i>
          <i class="apricon apricon-facebook apricon-stack-1x"></i>
        </span>
      </a></li>
      <li><a href="https://twitter.com/AnhTranngoc" target="_blank">
        <span class="apricon-stack">
          <i class="apricon apricon-circle-thin apricon-stack-2x"></i>
          <i class="apricon apricon-twitter apricon-stack-1x"></i>
        </span>
      </a></li>
      <li><a href="https://www.instagram.com/manhhomienbienthuy/" target="_blank">
        <span class="apricon-stack">
          <i class="apricon apricon-circle-thin apricon-stack-2x"></i>
          <i class="apricon apricon-instagram apricon-stack-1x"></i>
        </span>
      </a></li>
      <li><a href="https://github.com/manhhomienbienthuy" target="_blank">
        <span class="apricon-stack">
          <i class="apricon apricon-circle-thin apricon-stack-2x"></i>
          <i class="apricon apricon-github-alt apricon-stack-1x"></i>
        </span>
      </a></li>
    </ul>

    <p class="copyright">
      {% now 'Y' as current_year %}
      {% url 'about:us' as about_url %}
      {% blocktrans %}
        Copyright © 2016-{{ current_year }}
        <a href="{{ about_url }}">Anh Tranngoc</a>.
        All rights reserved.
      {% endblocktrans %}
    </p>

    <div class="language-switcher">
      <form action="{% url 'set_language' %}" method="post">
        {% csrf_token %}

        <input name="next" id="next" type="hidden"
          value="{{ request.path|slice:'3:' }}{% if request.GET %}?{{ request.GET.urlencode }}{% endif %}">

        <div id="js-language-switcher">
          {% get_current_language as LANGUAGE_CODE %}
          {% get_available_languages as LANGUAGES %}
          {% get_language_info_list for LANGUAGES as languages %}
          <ul>
            <li><i class="apricon apricon-globe"></i></li>
            {% for language in languages %}
              {% if language.code == LANGUAGE_CODE %}
                {% with url="#!" %}
                  <li>
                    <a href="{{ url }}">
                      {{ language.name_local }} ({{ language.code }})
                    </a>
                  </li>
                {% endwith %}
              {% else %}
                {% with current_prefix='/'|add:LANGUAGE_CODE|add:'/' %}
                {% with current_path=request.path|cut:current_prefix %}
                {% with url="/"|add:language.code|add:'/'|add:current_path %}
                  <li>
                    <a href="{{ url }}{% if request.GET %}?{{ request.GET.urlencode }}{% endif %}">
                      {{ language.name_local }} ({{ language.code }})
                    </a>
                  </li>
                {% endwith %}
                {% endwith %}
                {% endwith %}
              {% endif %}
            {% endfor %}
          </ul>
        </div>
      </form>
    </div>
  </div>
</footer>

templates/includes/header.html
{% load i18n %}

<header id="top">
  <div class="container">
    <a href="{% url 'homepage' %}" class="logo">Aprigi</a>
    <p class="meta">
      {% trans "The app for my April girl, from naa with love" %}
    </p>

    <div class="navigation-button">
      <i class="apricon apricon-bars"></i>
    </div>

    <div class="navigation active">
      <ul>
        <li{% if 'savings' in request.path %} class="active"{% endif %}>
          <a href="{% url 'savings:index' %}">{% trans "Savings" %}</a>
        </li>
        <li{% if 'expenses' in request.path %} class="active"{% endif %}>
          <a href="{% url 'expenses:index' %}">{% trans "Expense" %}</a>
        </li>

        {% if user.is_authenticated %}
          <li><a href="{% url 'logout'%}?next={{ request.path }}">
            {% trans "Logout" %}
          </a></li>
        {% else %}
          <li><a href="{% url 'login'%}?next={{ request.path }}">
            {% trans "Login" %}
          </a></li>
        {% endif %}
      </ul>
    </div>
  </div>
</header>

templates/includes/warning.html
{% load i18n %}

<noscript>
  <div class="warning">
    <div class="container">
      <p>
        <strong>{% trans "Notice" %}:</strong>
        {% blocktrans %}
          While JavaScript is not essential for this website, your
          interaction with the content will be limited. Please turn
          JavaScript on for the full experience.
        {% endblocktrans %}
      </p>
    </div>
  </div>
</noscript>

<!--[if lt IE 11]>
    <div class="warning">
      <div class="container">
        <p>
          <strong>{% trans "Notice" %}:</strong>
          {% blocktrans %}
            Your browser is <em>ancient</em>. Upgrade to a different
            browser to experience a better web.
          {% endblocktrans %}
        </p>
      </div>
    </div>
<![endif]-->